site_name: Документація НАНЦ
site_url: https://RyndinaOlena.github.io/vernadsky-docs/

extra_javascript:
  - assets/js/external-links.js

extra_css:
  - assets/css/custom.css

plugins:
  - search:
      lang: [en, ru] # uk не підтримується lunr.js
  - i18n:
      docs_structure: suffix
      default_language: uk
      languages:
        uk:
          name: Українська
          build: true
        en:
          name: English
          build: true
      nav_translations:
        en:
          Головна: Home
          Станція: Station
          Юридична інформація: Legal
          Напрями: Research Areas
          Огляд: Overview
          Магнітка: Geomagnetism
          Загальна інформація: Overview
          Інструменти: Instruments
          Формати: Formats
          Методики: Methods
          Метрологічний опис: Data description
          Особливості інтерпретації: Interpretation notes
          Публікації: Publications
          Атмосферний озон: Atmospheric Ozone
          Методики (Умкер): Methods (Umkehr)
          Формати/центри даних: Formats & Data Centers
          Публікації (UA/World): Publications (UA/World)
          Корисні посилання: Useful links

theme:
  name: material
  custom_dir: docs/overrides
  language: uk
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Перемкнути на темну тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Перемкнути на світлу тему

# Навігація для української
nav:
  - Головна: index.md
  - Станція: station.md
  - Юридична інформація: legal.md
  - Напрями:
      - Огляд: directions/index.md
      - Магнітка:
          - Загальна інформація: directions/magnetics/index.md
          - Інструменти: directions/magnetics/instruments.md
          - Формати: directions/magnetics/formats.md
          - Методики: directions/magnetics/methods.md
          - Метрологічний опис: directions/magnetics/data-description.md
          - Особливості інтерпретації: directions/magnetics/interpretation.md
          - Публікації: directions/magnetics/results.md
      - Атмосферний озон:
          - Загальна інформація: directions/ozone/index.md
          - Інструменти: directions/ozone/instruments.md
          - Методики (Умкер): directions/ozone/methods.md
          - Формати/центри даних: directions/ozone/formats.md
          - Публікації (UA/World): directions/ozone/results.md
          - Корисні посилання: directions/ozone/links.md
